title: 'Legal Aid Bureau'
description: Description
url: 'https://lab.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
favicon: /images/favicon-minlaw.ico
google-analytics: UA-10405444-12
permalink: none
baseurl: ""
defaults:
  -
    scope:
      path: ""
    values:
      layout: page
staging: https://mlaw-lab-staging.netlify.com/
prod: https://mlaw-lab-prod.netlify.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
